version: '3.6' 
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    env_file:
      - .env
    image: postgres:9.6
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/postgresql/data

  # EFK
  fluentd:
    build: ./config/fluentd
    volumes:
      - ./config/fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - 9200:9200
  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
  portfolio:
    env_file:
      - .env
    build: ./
    command: bundle exec puma -C ./config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - ./:/portfolio
      - gems-portfolio:/bundle
    depends_on:
      - postgres
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: portfolio.access
volumes:
  db-data:
  gems-portfolio:
