version: '3.6' 
services:
  postgres:
    env_file:
      - .env
    image: postgres:9.6
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/postgresql/data
  portfolio:
    env_file:
      - .env
    build: ./
    command: bundle exec puma -C ./config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - ./:/portfolio
      - gems-portfolio:/bundle
    depends_on:
      - postgres
volumes:
  db-data:
  gems-portfolio:
