# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_username: <%= ENV["AUTH_USERNAME"] %>
  auth_password: <%= ENV["AUTH_PASSWORD"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  database_password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_username: <%= ENV["AUTH_USERNAME"] %>
  auth_password: <%= ENV["AUTH_PASSWORD"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  database_password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_username: <%= ENV["AUTH_USERNAME"] %>
  auth_password: <%= ENV["AUTH_PASSWORD"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  database_password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
